In [1]:
a_dict = {'one':1}

In [2]:
a_dict

{'one': 1}

In [3]:
a_dict['two'] = 2

In [4]:
a_dict

{'one': 1, 'two': 2}

In [5]:
if 'three' in a_dict:
    print(a_dict['three'])
else:
    print('three is not there')

three is not there


In [6]:
del a_dict['one']

In [7]:
a_dict

{'two': 2}

In [8]:
Dict = dict([(1, 'Geeks'), (2, 'For')]) 

In [9]:
Dict

{1: 'Geeks', 2: 'For'}

In [10]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()

query_scores = student_marks[query_name]
print("{0:.2f}".format(sum(query_scores)/(len(query_scores))))

 2
 Harsh 25 26.5 28
 Anurag 26 28 30
 Harsh


26.50


In [11]:
student_marks

{'Harsh': [25.0, 26.5, 28.0], 'Anurag': [26.0, 28.0, 30.0]}

In [12]:
s = [1,2,3,4]

In [14]:
list(map(float,s))

[1.0, 2.0, 3.0, 4.0]

In [17]:
my_list = []

In [21]:
n =input()
my_list.insert(0,n)

 12


In [22]:
print(f'insert 0 {n}')

insert 0 12


In [36]:
x = input().split()

 sdf asdf asdf


In [37]:
x

['sdf', 'asdf', 'asdf']

In [34]:
x = input().split(" ")

 sdf sdf asdf


In [35]:
x

['sdf', 'sdf', 'asdf']

In [39]:
' '.join(x)

'sdf asdf asdf'

In [41]:
x = [1,2,3,4]

In [52]:
x[::-1]

[4, 3, 2, 1]

In [57]:
t = (1,2)

In [59]:
3713081631934410656 == hash(t)

True

In [63]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    t = hash(tuple(integer_list))
    print(t)
    


 2
 1 2


3713081631934410656


(1, 2)

In [1]:
import numpy as np

In [7]:
np.ones((1,2), dtype=int )

array([[1, 1]])

In [11]:
x,y,z = tuple(map(int,input().split()))

 3 3 3


 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [66]:
str_1 =' Www.HackerRank.com'.strip()

In [67]:
str_1

'Www.HackerRank.com'

In [60]:
ord('A')

65

In [61]:
97-65

32

In [84]:
upper_list = []
lower_list = []


In [109]:
str_1 = ' Www.HackerRank.com'.strip()
final_list = 
for i in range(len(str_1)):
    if str_1[i].islower():
        str_1[i].upper()
        final_list += str_1[i]
    elif str_1[i].isupper():
        final_list += str_1[i]

result = ''.join(final_list)      
print(f'{str_1} presents "{result}"')
    
        

UnboundLocalError: local variable 'final_list' referenced before assignment

'WwwHackerRankcom'

In [104]:
final_list

['W',
 'w',
 'w',
 'H',
 'a',
 'c',
 'k',
 'e',
 'r',
 'R',
 'a',
 'n',
 'k',
 'c',
 'o',
 'm']

In [112]:
def swap_case(s):
    a = ""
    for i in s:
        if i.isupper() == True:
            a+=(i.lower())
        else:
            a+=(i.upper())
    return a

In [114]:
result = swap_case(' Www.HackerRank.com')

In [115]:
string = 'this is a string '

In [117]:
'-'.join(string.split())

'this-is-a-string'

In [ ]:
i

In [119]:
string= 'ABCDCDC'
sub = 'CDC'

In [127]:
count = 0
for i in string:
    if


SyntaxError: can't assign to literal (<ipython-input-127-149bf0e89c88>, line 2)

In [131]:
string.split('CDC')

['AB', 'DC']

In [134]:
ind=string.find(sub)

In [139]:
s =string[ind+1:]

In [140]:
ind=s.find(sub)

In [141]:
ind

1

In [2]:
s = "qA2"

True

In [5]:
s.isalpha()

False

In [6]:
result = ["False", "False", "False", "False", "False"]

In [14]:
print('\n'.join(result))

False
False
False
False
False


In [15]:
print(5) if 5 < 6 else print(6)

5


In [17]:
print('True') if s.isalnum() else print('False')
print('True') if s.isalpha() else print('False')
print('True') if s.isdigit() else print('False')
print('True') if s.islower() else print('False')
print('True') if s.isupper() else print('False')

True
False
False
False
False


In [18]:
    for i in s:
        if i.isalnum():
            result[0] = "True"
        if i.isalpha():
            result[1] = "True"
        if i.isdigit():
            result[2] = "True"
        if i.islower():
            result[3] = "True"
        if i.isupper():
            result[4] = "True"
    print(*result, sep="\n")

True
True
True
True
True


In [19]:
print('True') if s.isupper() else print('False')

False
